name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "2.0.0-prelease"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38a5492e4e0dd1f6f60f09ece0e06dd7cf66bcc641763ecba778972da530c425"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
