name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "2.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dba633820d3032c3348767fe03cff7e106a4e6c9dc9d09d38e3722fc4e845ca"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
