MINECRAFT_VERSION="1.20.4"
PUBLISH_DIRECTORY="./publish/$MINECRAFT_VERSION"
BASE_DIRECTORY="./base"
FO_BASE_DIRECTORY="./base-fo/Packwiz/$MINECRAFT_VERSION"

if [ -d $PUBLISH_DIRECTORY ]; then
    rm -rf $PUBLISH_DIRECTORY
fi

mkdir -p $PUBLISH_DIRECTORY

cp -R "$FO_BASE_DIRECTORY/*" "$PUBLISH_DIRECTORY/"
cp -Rf "$BASE_DIRECTORY/*" "$PUBLISH_DIRECTORY/"

PREVIOUS=pwd
cd $PUBLISH_DIRECTORY
packwiz modrinth export
cd $PREVIOUS