name = "Nesquate Server's Client Modpack"
author = "Nesquate"
version = "1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c0ad5d978c1e7b962eb44cc04a01fdc1c078b8185453ae8f15e612d870724e2"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.3-Snapshot"]
