name = "Nesquate's Modpack"
author = "Nesquate"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d38f590bbe1b7b9e44bd2bddeb733038e1afb6c3da596fb282611d770c2539"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
