name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "3.0.0-m1.20240700"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3929db27941bc9fe77ff17b475a634db3ba298b9b8fda548dce421c3eee8839"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
