name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "3.0.0-m1.20240700"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c72cb05a260bb5ebb0eb3c277966d1a578ddb2c574021d30955a6792de43f6d"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
