name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "3.0.0-m1.20240700"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5610a9eb3bd824e38443ef06343c05580ccafaa75cf36bceac9ee3db8a5de26d"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
