name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "3.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff62fb6e1811e233317b700e7dc3582d4463690d171d62783e27ac10c5c692a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = []
