name = "Nesquate's Lazy Modpack"
author = "Nesquate"
version = "2.0.0-edge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9379e1eb6035ae3a073fb4ad1e7f5c2625a6f029c542067cc4a8c3ae4faf8e6a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.3"]
